cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    admin:
      email: test@test.comemail
      name: admin
      password: $2b$12$Nbypzd9dZaYsV0u9gvnQReOtBOJKUyGBVc5mK6oMsA.5IGFVResCe
    member:
      email: chongjie.zhong@zealcomm.cn
      name: Rebecca Briggs
      password: $2b$12$ZddjvjReprbmI5EulYLRA.FdoplGcsowhHNjf9YRZCCMixef0tqlW
    someuser:
      email: good@good.com
      name: gooduser
      password: $2b$12$Acx09sANmGhZgi1oyEO8MOnSWkpcOx1LyueJTPtNFld8LBXxtuYdS
preauthorized:
  emails:
  - chongjie.zhong@zealcomm.cn
